//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulingSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulingSystem.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment added successfully!.
        /// </summary>
        internal static string AppointmentAddSuccess {
            get {
                return ResourceManager.GetString("AppointmentAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Reminder: You have an appointment at {0}..
        /// </summary>
        internal static string AppointmentAlert {
            get {
                return ResourceManager.GetString("AppointmentAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment deleted successfully!.
        /// </summary>
        internal static string AppointmentDeleteSuccess {
            get {
                return ResourceManager.GetString("AppointmentDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment updated successfully!.
        /// </summary>
        internal static string AppointmentUpdateSuccess {
            get {
                return ResourceManager.GetString("AppointmentUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        internal static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City added successfully!.
        /// </summary>
        internal static string CityAddSuccess {
            get {
                return ResourceManager.GetString("CityAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country added successfully!.
        /// </summary>
        internal static string CountryAddSuccess {
            get {
                return ResourceManager.GetString("CountryAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time Zone:.
        /// </summary>
        internal static string CurrentTimeZoneLabel {
            get {
                return ResourceManager.GetString("CurrentTimeZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer added successfully!.
        /// </summary>
        internal static string CustomerAddSuccess {
            get {
                return ResourceManager.GetString("CustomerAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer deleted successfully!.
        /// </summary>
        internal static string CustomerDeleteSuccess {
            get {
                return ResourceManager.GetString("CustomerDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer updated successfully!.
        /// </summary>
        internal static string CustomerUpdateSuccess {
            get {
                return ResourceManager.GetString("CustomerUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address can only contain letters, numbers, and dashes..
        /// </summary>
        internal static string ErrorAddress {
            get {
                return ResourceManager.GetString("ErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        internal static string ErrorAddressRequired {
            get {
                return ResourceManager.GetString("ErrorAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment is already booked on {0} between {1} and {2}. Please select another appointment time..
        /// </summary>
        internal static string ErrorAppointmentExists {
            get {
                return ResourceManager.GetString("ErrorAppointmentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name can only include letters..
        /// </summary>
        internal static string ErrorCity {
            get {
                return ResourceManager.GetString("ErrorCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or add a city..
        /// </summary>
        internal static string ErrorCityRequired {
            get {
                return ResourceManager.GetString("ErrorCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact is required..
        /// </summary>
        internal static string ErrorContactRequired {
            get {
                return ResourceManager.GetString("ErrorContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name can only include letters..
        /// </summary>
        internal static string ErrorCountry {
            get {
                return ResourceManager.GetString("ErrorCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or add a country..
        /// </summary>
        internal static string ErrorCountryRequired {
            get {
                return ResourceManager.GetString("ErrorCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer..
        /// </summary>
        internal static string ErrorCustomerRequired {
            get {
                return ResourceManager.GetString("ErrorCustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date..
        /// </summary>
        internal static string ErrorDateRequired {
            get {
                return ResourceManager.GetString("ErrorDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment must be scheduled during the business hours of 9:00 a.m. to 5:00 p.m. EST, Monday–Friday..
        /// </summary>
        internal static string ErrorDateTime {
            get {
                return ResourceManager.GetString("ErrorDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        internal static string ErrorDescRequired {
            get {
                return ResourceManager.GetString("ErrorDescRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an appointment duration of 15 minutes, 30 minutes, or 60 minutes..
        /// </summary>
        internal static string ErrorDuration {
            get {
                return ResourceManager.GetString("ErrorDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration is required..
        /// </summary>
        internal static string ErrorDurationRequired {
            get {
                return ResourceManager.GetString("ErrorDurationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location..
        /// </summary>
        internal static string ErrorLocation {
            get {
                return ResourceManager.GetString("ErrorLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location..
        /// </summary>
        internal static string ErrorLocationRequired {
            get {
                return ResourceManager.GetString("ErrorLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        internal static string ErrorMsgGeneral {
            get {
                return ResourceManager.GetString("ErrorMsgGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must contain only letters..
        /// </summary>
        internal static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string ErrorNameRequired {
            get {
                return ResourceManager.GetString("ErrorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password do not match..
        /// </summary>
        internal static string ErrorNoMatch {
            get {
                return ResourceManager.GetString("ErrorNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        internal static string ErrorNoPassword {
            get {
                return ResourceManager.GetString("ErrorNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username..
        /// </summary>
        internal static string ErrorNoUsername {
            get {
                return ResourceManager.GetString("ErrorNoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username and password..
        /// </summary>
        internal static string ErrorNoUsernamePassword {
            get {
                return ResourceManager.GetString("ErrorNoUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number can only include digits and dashes..
        /// </summary>
        internal static string ErrorPhone {
            get {
                return ResourceManager.GetString("ErrorPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be between 10 and 15 digits..
        /// </summary>
        internal static string ErrorPhoneLength {
            get {
                return ResourceManager.GetString("ErrorPhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        internal static string ErrorPhoneRequired {
            get {
                return ResourceManager.GetString("ErrorPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code can only include numbers..
        /// </summary>
        internal static string ErrorPostalCode {
            get {
                return ResourceManager.GetString("ErrorPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is required..
        /// </summary>
        internal static string ErrorPostalCodeRequired {
            get {
                return ResourceManager.GetString("ErrorPostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code must include between 3 and 10 digits..
        /// </summary>
        internal static string ErrorPostalLength {
            get {
                return ResourceManager.GetString("ErrorPostalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an appointment in the Appointment table to update or delete..
        /// </summary>
        internal static string ErrorSelectAppointment {
            get {
                return ResourceManager.GetString("ErrorSelectAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer in the Customer table to update or delete..
        /// </summary>
        internal static string ErrorSelectCustomer {
            get {
                return ResourceManager.GetString("ErrorSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a time..
        /// </summary>
        internal static string ErrorTimeRequired {
            get {
                return ResourceManager.GetString("ErrorTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title can only contain letters..
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string ErrorTitleRequired {
            get {
                return ResourceManager.GetString("ErrorTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment type can only contain letters..
        /// </summary>
        internal static string ErrorType {
            get {
                return ResourceManager.GetString("ErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment type is required..
        /// </summary>
        internal static string ErrorTypeRequired {
            get {
                return ResourceManager.GetString("ErrorTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required..
        /// </summary>
        internal static string ErrorUrlRequired {
            get {
                return ResourceManager.GetString("ErrorUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        internal static string ErrorUsernameExists {
            get {
                return ResourceManager.GetString("ErrorUsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect. Please try again..
        /// </summary>
        internal static string ErrorUsernameOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("ErrorUsernameOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active:.
        /// </summary>
        internal static string LabelActive {
            get {
                return ResourceManager.GetString("LabelActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a City.
        /// </summary>
        internal static string LabelAddCity {
            get {
                return ResourceManager.GetString("LabelAddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Country.
        /// </summary>
        internal static string LabelAddCountry {
            get {
                return ResourceManager.GetString("LabelAddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Address:.
        /// </summary>
        internal static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2:.
        /// </summary>
        internal static string LabelAddress2 {
            get {
                return ResourceManager.GetString("LabelAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string LabelAppointments {
            get {
                return ResourceManager.GetString("LabelAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Hours: 9:00 AM - 5:00 PM EST, Mon-Fri.
        /// </summary>
        internal static string LabelBusinessHours {
            get {
                return ResourceManager.GetString("LabelBusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string LabelCalendar {
            get {
                return ResourceManager.GetString("LabelCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * City:.
        /// </summary>
        internal static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name:.
        /// </summary>
        internal static string LabelCityName {
            get {
                return ResourceManager.GetString("LabelCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Contact.
        /// </summary>
        internal static string LabelContact {
            get {
                return ResourceManager.GetString("LabelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Country:.
        /// </summary>
        internal static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Country Name:.
        /// </summary>
        internal static string LabelCountryName {
            get {
                return ResourceManager.GetString("LabelCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string LabelCustomer {
            get {
                return ResourceManager.GetString("LabelCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Management.
        /// </summary>
        internal static string LabelCustomerManagement {
            get {
                return ResourceManager.GetString("LabelCustomerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Date.
        /// </summary>
        internal static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Description.
        /// </summary>
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Duration (minutes).
        /// </summary>
        internal static string LabelDuration {
            get {
                return ResourceManager.GetString("LabelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Location.
        /// </summary>
        internal static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Name:.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Phone:.
        /// </summary>
        internal static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Postal Code:.
        /// </summary>
        internal static string LabelPostalCode {
            get {
                return ResourceManager.GetString("LabelPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string LabelReports {
            get {
                return ResourceManager.GetString("LabelReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string LabelReportType {
            get {
                return ResourceManager.GetString("LabelReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Required Fields.
        /// </summary>
        internal static string LabelReqFields {
            get {
                return ResourceManager.GetString("LabelReqFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Time.
        /// </summary>
        internal static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Title.
        /// </summary>
        internal static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Type.
        /// </summary>
        internal static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * URL.
        /// </summary>
        internal static string LabelUrl {
            get {
                return ResourceManager.GetString("LabelUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily View.
        /// </summary>
        internal static string RadioBtnDailyView {
            get {
                return ResourceManager.GetString("RadioBtnDailyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly View.
        /// </summary>
        internal static string RadioBtnMonthlyView {
            get {
                return ResourceManager.GetString("RadioBtnMonthlyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully!.
        /// </summary>
        internal static string UserRegisteredSuccess {
            get {
                return ResourceManager.GetString("UserRegisteredSuccess", resourceCulture);
            }
        }
    }
}
